uint8 HW_RESET_IMMEDIATELY=0
uint8 SW_RESET_CONTROLLED=1
uint8 SW_RESET_CONTROLLED_GNSS=2
uint8 HW_RESET_AFTER_SHUTDOWN=4
uint8 GNSS_STOP_CONTROLLED=8
uint8 GNSS_START_CONTROLLED=9
uint8 reset_type
---
