name: ros2-foxy-rosbag
version: '0.3.5+git'
summary: rosbag2 tool from ROS2 Foxy, and extras
description: |
  This allows portable use of the `ros2 bag` tool from ROS2 Foxy, very useful when a native installation is not available.

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64

hooks:
  configure:
    plugs: [network,network-bind]

# Fix /dev/shm access for fastRTPS
plugs:
  shared-memory:
    private: true

parts:
  hook-scripts:
    plugin: dump
    source: ./hooks/
    organize:
      config-manager.sh: usr/bin/config-manager
      configure.sh: snap/hooks/configure

  wrapper-scripts:
    plugin: dump
    source: ./wrappers/
    organize:
      ros2-custom-ws.sh: usr/bin/ros2-custom-ws

  ros-app:
    plugin: colcon
    source: ./src
    build-packages:
      - curl
      - git
      - libasio-dev
      - libatlas-base-dev
      - libcunit1-dev
      - libcurl-dev
      - libpython3-dev
      - libssl-dev
      - libtinyxml2-dev
      - libusb-1.0-0-dev
      - lsb-core
      - lsb-release
      - openssl
      - python3-argcomplete
      - python3-colcon-common-extensions
      - python3-numpy
      - ros-foxy-rmw
      - ros-foxy-ros-base
      - ros-foxy-ros2bag
      - ros-foxy-ros2launch
      - ros-foxy-rosbag2-storage
      - ros-foxy-rosbag2-storage-default-plugins
      - ros-foxy-rosbag2-transport
      - ros-foxy-rosbridge-server
      - ros-foxy-rosbridge-suite
      - ros-foxy-rosidl-typesupport-connext-c
      - ros-foxy-rosidl-typesupport-connext-cpp
      - ros-foxy-rosidl-typesupport-fastrtps-c
      - ros-foxy-rosidl-typesupport-fastrtps-cpp
      - ros-foxy-geometry-msgs
    stage-packages: 
      - curl
      - git
      - libasio-dev
      - libatlas-base-dev
      - libcunit1-dev
      - libcurl-dev
      - libpython3-dev
      - libssl-dev
      - libtinyxml2-dev
      - libusb-1.0-0-dev
      - lsb-core
      - lsb-release
      - openssl
      - python3-argcomplete
      - python3-colcon-common-extensions
      - python3-numpy
      - ros-foxy-rmw
      - ros-foxy-ros-base
      - ros-foxy-ros2bag
      - ros-foxy-ros2launch
      - ros-foxy-rosbag2-storage
      - ros-foxy-rosbag2-storage-default-plugins
      - ros-foxy-rosbag2-transport
      - ros-foxy-rosbridge-server
      - ros-foxy-rosbridge-suite
      - ros-foxy-rosidl-typesupport-connext-c
      - ros-foxy-rosidl-typesupport-connext-cpp
      - ros-foxy-rosidl-typesupport-fastrtps-c
      - ros-foxy-rosidl-typesupport-fastrtps-cpp
      - ros-foxy-geometry-msgs

    filesets:
      nocron: [ -var/spool/cron ]

    prime:
      - $nocron

layout:
  /opt/rti.com:
    bind: $SNAP/opt/rti.com

# Point to the correct libraries folder.
#  - Important for libblas.so.3
#  - Important for /opt/vc (VideoCore) camera drivers
environment:
  "LD_LIBRARY_PATH": "$SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/atlas"
  "ROS_HOME": "$SNAP_USER_DATA" # remap HOME for rospack

apps:
  colcon:
    command: usr/bin/colcon
    extensions: [ros2-foxy]
    plugs: [home, network, network-bind, shared-memory]

  ros2:
    command: usr/bin/ros2-custom-ws
    plugs: [home, network, network-bind, shared-memory]
    extensions: [ros2-foxy]

  rosbridge-server:
    command: opt/ros/foxy/bin/ros2 launch rosbridge_server rosbridge_websocket_launch.xml
    plugs: [network, network-bind, home, shared-memory]
    extensions: [ros2-foxy]
