name: ros2-foxy-rosbag
version: '0.3'
summary: rosbag2 tool from ROS2 Foxy
description: |
  This allows portable use of the `ros2 bag` tool from ROS2 Foxy, very useful when a native installation is not available.

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

parts:
  ros-demos:
    plugin: colcon
    source: ./src
    stage-packages: 
      - ros-foxy-ros2launch
      - ros-foxy-ros2bag
      - ros-foxy-ros-base
      - libpython3-dev
      - python3-argcomplete
      - ros-foxy-rosbag2-storage
      - ros-foxy-rosbag2-storage-default-plugins
      - ros-foxy-rosbag2-transport
      - libasio-dev
      - libtinyxml2-dev
      - libcunit1-dev
      - ros-foxy-rmw
      - ros-foxy-rosidl-typesupport-connext-c
      - ros-foxy-rosidl-typesupport-connext-cpp
      - libatlas-base-dev
      - lsb-core
      - lsb-release

    filesets:
      nocron: [ -var/spool/cron ]

    prime:
      - $nocron

layout:
  /opt/rti.com:
    bind: $SNAP/opt/rti.com

# Point to the correct libraries folder.
#  - Important for libblas.so.3
#  - Important for /opt/vc (VideoCore) camera drivers
environment:
  "LD_LIBRARY_PATH": "$SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
  "ROS_HOME": "$SNAP_USER_DATA" # remap HOME for rospack

apps:
  bag:
    command: opt/ros/foxy/bin/ros2 bag
    plugs: [network, network-bind] 
    extensions: [ros2-foxy]
  ros2:
    command: opt/ros/foxy/bin/ros2
    plugs: [network, network-bind] 
    extensions: [ros2-foxy]
