name: ros2-foxy-rosbag
version: '0.3.4+git'
summary: rosbag2 tool from ROS2 Foxy, and extras
description: |
  This allows portable use of the `ros2 bag` tool from ROS2 Foxy, very useful when a native installation is not available.

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64

hooks:
  configure:
    plugs: [network,network-bind]

parts:
  hook-scripts:
    plugin: dump
    source: ./hooks/
    organize:
      config-manager.sh: usr/bin/config-manager
      configure.sh: snap/hooks/configure

  wrapper-scripts:
    plugin: dump
    source: ./wrappers/
    organize:
      ros2-custom-ws.sh: usr/bin/ros2-custom-ws

  ros-app:
    plugin: colcon
    source: ./src
    build-packages:
      - openssl
      - curl
      - libcurl-dev
      - ros-foxy-ros-base
      - ros-foxy-rosidl-typesupport-fastrtps-c
      - ros-foxy-rosbag2-storage
      - libssl-dev
      - git
      - libusb-1.0-0-dev
    stage-packages: 
      - libusb-1.0-0-dev
      - ros-foxy-ros2launch
      - ros-foxy-ros2bag
      - ros-foxy-ros-base
      - ros-foxy-rosbridge-suite
      - ros-foxy-rosbridge-server
      - libpython3-dev
      - python3-argcomplete
      - python3-numpy
      - ros-foxy-rosbag2-storage
      - ros-foxy-rosbag2-storage-default-plugins
      - ros-foxy-rosbag2-transport
      - libasio-dev
      - libtinyxml2-dev
      - libcunit1-dev
      - ros-foxy-rmw
      - ros-foxy-rosidl-typesupport-connext-c
      - ros-foxy-rosidl-typesupport-connext-cpp
      - libatlas-base-dev
      - lsb-core
      - lsb-release

    filesets:
      nocron: [ -var/spool/cron ]

    prime:
      - $nocron

layout:
  /opt/rti.com:
    bind: $SNAP/opt/rti.com

# Point to the correct libraries folder.
#  - Important for libblas.so.3
#  - Important for /opt/vc (VideoCore) camera drivers
environment:
  "LD_LIBRARY_PATH": "$SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/atlas"
  "ROS_HOME": "$SNAP_USER_DATA" # remap HOME for rospack

apps:
  ros2:
    command: usr/bin/ros2-custom-ws
    plugs: [home, network, network-bind]
    extensions: [ros2-foxy]

  ros2-no-custom-ws:
    command: opt/ros/foxy/bin/ros2
    plugs: [home, network, network-bind] 
    extensions: [ros2-foxy]

  rosbridge-server:
    command: opt/ros/foxy/bin/ros2 launch rosbridge_server rosbridge_websocket_launch.xml
    plugs: [network, network-bind]
    extensions: [ros2-foxy]
